
import { GenerateContentResponse, Chat as GeminiChat, Part } from "@google/genai";

export interface DvachFile {
  name: string;
  path: string;
  thumbnail: string;
  md5: string;
  type: number; // 0: image, 10: webm video with sound, etc.
  width: number;
  height: number;
  size: number; // in bytes
  tn_width: number;
  tn_height: number;
}
export interface DvachPost {
  num: string; // Can be string or number from API, ensure consistent usage
  parent: string;
  comment: string;
  timestamp: number;
  files?: DvachFile[];
  subject?: string;
  name?: string; // Poster name
  lasthit?: number; // Timestamp of last reply, for OP
  op?: number; // 1 if OP
}

export interface DvachThreadData { // Structure for board/res/thread.json
  posts: DvachPost[];
  current_thread: string;
  // other thread-specific fields if any
}
export interface DvachCatalogThread { // Structure for catalog.json
    num: string;
    comment: string;
    timestamp: number;
    subject: string;
    views: number;
    posts_count: number;
    files_count: number;
    files?: DvachFile[]; // Typically one preview file
    op?: number;
    name?: string;
}

export interface DvachThread { // Used by getDvachThread, which fetches board/res/thread.json
  threads: DvachThreadData[]; // This is an array with one element for the specific thread
  // It can also represent the catalog structure if fetching catalog.json
  // For simplicity, let's assume getDvachThread fetches a single thread structure like thread.json
  // If fetching catalog.json, the structure is different: an object with board info and a `threads` array of DvachCatalogThread
}


export interface SentMessageInfo {
  num: string; 
  timestamp: number; 
  comment: string;
  file_hash?: string;
  parent?: string; 
  board: string;
  thread: string;
  isGeminiPost?: boolean; // True if this post was generated by Gemini
  geminiTriggerPostNum?: string; // If Gemini replied to a specific post
  geminiConversationId?: string; // To link to a specific Gemini chat session if applicable
}

export interface AppSettings {
  board: string;
  threadId: string;
  passcode: string;
  geminiApiKeySource: 'env' | 'user';
  userGeminiApiKey: string;
  useRandomDelayNormal: boolean;
  useRandomDelaySecure: boolean;
  allowReplyToSelf: boolean;
  currentDomainIndex: number;
  theme: 'light' | 'dark' | 'system';
  geminiReplyWithImage: boolean; 
  autoMonitorDvachThreadForGemini: boolean;
  proxyMode: 'cors-anywhere' | 'custom' | 'none'; // New proxy setting
  customProxyUrl: string; // New proxy setting for custom URL
}

export interface LogEntry {
  id: string;
  timestamp: number;
  message: string;
  type: 'info' | 'error' | 'success' | 'warning' | 'gemini' | 'dvach';
  data?: unknown;
}

export enum PostMode {
  // ... existing modes
  GEMINI_REPLY_TO_POST = "gemini_reply_to_post",
  GEMINI_CONVERSATIONAL_REPLY = "gemini_conversational_reply",
  GEMINI_RANDOM_POST_REPLY = "gemini_random_post_reply",
}

export enum GeminiFeature {
  GENERATE_CONTENT = "generateContent",
  GENERATE_CONTENT_STREAM = "generateContentStream",
  CHAT = "chat",
  CHAT_STREAM = "chatStream",
  IMAGE_GENERATION = "imageGeneration",
}

export interface ChatMessage {
  role: 'user' | 'model' | 'system'; // System role for Gemini Chat
  parts: Part[]; // Using Gemini's Part type
  timestamp: number;
  imagePreview?: string; // base64 data URL for displaying sent/received images in chat UI
}

export interface ActiveTask {
  id: string;
  type: string; 
  description: string;
  stop: () => void; 
}

export type GeminiChatInstance = GeminiChat;

export interface GeneratedImage {
  image: {
    imageBytes: string; 
    mimeType: string;
  };
  altText?: string;
}

export interface GroundingChunk {
  web?: {
    uri?: string; 
    title?: string; 
  };
  retrievedContext?: {
    uri?: string; 
    title?: string; 
  };
}

export interface GroundingMetadata {
  webSearchQueries?: string[];
  groundingChunks?: GroundingChunk[];
}

export interface CustomGenerateContentResponse extends GenerateContentResponse {
   candidates?: (GenerateContentResponse['candidates'][0] & { groundingMetadata?: GroundingMetadata })[];
}

// For Gemini-Dvach conversations
export interface GeminiDvachConversation {
  dvachRootPostByGeminiNum: string; // The Dvach post number where Gemini started this conversation
  board: string;
  threadId: string;
  geminiChatInstance?: GeminiChatInstance; // Stored chat instance
  history: ChatMessage[]; // Full history including initial prompt
  lastCheckedTimestamp: number; // To know when we last looked for replies
}
